"""create market_prices table

Revision ID: 3198d2bbad71
Revises: ce52b0087f27
Create Date: 2026-04-29 19:21:45.932609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3198d2bbad71'
down_revision: Union[str, Sequence[str], None] = 'ce52b0087f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume_24h', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_time', 'market_prices', ['asset_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_market_prices_asset_id'), 'market_prices', ['asset_id'], unique=False)
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('ix_market_prices_observed_at'), 'market_prices', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_prices_observed_at'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_asset_id'), table_name='market_prices')
    op.drop_index('idx_asset_time', table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
