"""add decision-signal relationship

Revision ID: 5ff9d56cb8cb
Revises: 7135c5f4aef4
Create Date: 2026-05-02 20:14:22.149863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ff9d56cb8cb'
down_revision: Union[str, Sequence[str], None] = '7135c5f4aef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_decision_asset_time', 'decisions', ['asset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_decisions_asset_id'), 'decisions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.add_column('market_signals', sa.Column('decision_id', sa.Integer(), nullable=True))
    op.create_index('idx_signal_decision', 'market_signals', ['decision_id'], unique=False)
    op.create_index(op.f('ix_market_signals_decision_id'), 'market_signals', ['decision_id'], unique=False)
    op.create_foreign_key(None, 'market_signals', 'decisions', ['decision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market_signals', type_='foreignkey')
    op.drop_index(op.f('ix_market_signals_decision_id'), table_name='market_signals')
    op.drop_index('idx_signal_decision', table_name='market_signals')
    op.drop_column('market_signals', 'decision_id')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_asset_id'), table_name='decisions')
    op.drop_index('idx_decision_asset_time', table_name='decisions')
    op.alter_column('decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
