"""create market_signals table

Revision ID: de335e8404ba
Revises: 3198d2bbad71
Create Date: 2026-04-30 18:24:54.322170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de335e8404ba'
down_revision: Union[str, Sequence[str], None] = '3198d2bbad71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('signal_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_asset_time', 'market_signals', ['asset_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_market_signals_asset_id'), 'market_signals', ['asset_id'], unique=False)
    op.create_index(op.f('ix_market_signals_detected_at'), 'market_signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_market_signals_id'), 'market_signals', ['id'], unique=False)
    op.create_index(op.f('ix_market_signals_signal_type'), 'market_signals', ['signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_signals_signal_type'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_id'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_detected_at'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_asset_id'), table_name='market_signals')
    op.drop_index('idx_signal_asset_time', table_name='market_signals')
    op.drop_table('market_signals')
    # ### end Alembic commands ###
