# Signal Types (standardized, uppercase)
PRICE_SPIKE = "PRICE_SPIKE"
RSI_OVERBOUGHT = "RSI_OVERBOUGHT"
RSI_OVERSOLD = "RSI_OVERSOLD"

MA_BULLISH_CROSSOVER = "MA_BULLISH_CROSSOVER"
MA_BEARISH_CROSSOVER = "MA_BEARISH_CROSSOVER"