# Signal Types (standardized, uppercase)
PRICE_SPIKE = "PRICE_SPIKE"
RSI_OVERBOUGHT = "RSI_OVERBOUGHT"
RSI_OVERSOLD = "RSI_OVERSOLD"
MA_BULLISH_CROSSOVER = "MA_BULLISH_CROSSOVER"
MA_BEARISH_CROSSOVER = "MA_BEARISH_CROSSOVER"

# DECISIONS

BUY = "BUY"

SELL = "SELL"

HOLD = "HOLD"

# SCORING WEIGHTS

SIGNAL_WEIGHTS = {

    MA_BULLISH_CROSSOVER: 2,

    MA_BEARISH_CROSSOVER: -2,

    RSI_OVERSOLD: 1,

    RSI_OVERBOUGHT: -1,

    PRICE_SPIKE: -2,

}